### ISSUE TITLE
Needs a make restart option

### ISSUE THREAD

**Issue by dbbaskette** [jpatel-pivotal/hdb-docker#3]
Couple of times I have had the docker daemon stop and restart.   The containers are already created then, but just need to be re-run.   Current method is to start them manually.

**Comment by jpatel-pivotal** [comment]
you can do a make stop; make start to restart them all.

If you already have the containers created and they are stopped, you could just do amke start to start them up. 

Let me know if that works. 

I will also try a Docker daemon restart and let you know if the make file covers that case.
